name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: Build
      run: cargo build --verbose

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

    - name: Clippy (library)
      uses: actions-rs/clippy-check@v1
      with:
        name: Clippy (library)
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clippy (tests)
      uses: actions-rs/clippy-check@v1
      with:
        name: Clippy (tests)
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --tests

    - name: Rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Build Docs
      uses: actions-rs/cargo@v1
      with:
        command: doc

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
